# Generated by Django 5.0.6 on 2024-05-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais_origen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.pais', verbose_name='país de origen'),
        ),
        migrations.AddField(
            model_name='pais',
            name='nombre',
            field=models.CharField(default=50, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
