# Generated by Django 5.0.6 on 2024-05-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_rename_cliente_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='puesto_origen_id',
            new_name='puesto_id',
        ),
    ]
