# Generated by Django 5.0.6 on 2024-05-13 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_rename_puesto_origen_id_empleado_puesto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puesto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleado.puesto', verbose_name='Puesto de trabajo'),
        ),
    ]
